### ISSUE TITLE
Linux compatability

### ISSUE THREAD

**Issue by vandenheuvel** [openefsa/catalogue-browser#4]
Does this software also work on linux? If so, would anyone be so kind as to provide a few pointers for installation?

Or, is there some other API through which the data can be reached? A HTTP API, or database that I could connect to?

**Comment by AlbanShahajEFSA** [comment]
Yes it is possible to launch the tool in the Linux system but this will not be automatically updated since we are currently not supporting other operating systems except for Windows OS.

For launching the tool in Linux please download from the release page the "only app" package for your architecture. Once the donwload is completed extract the package and launch the ".jar" file (Java must be installed for this reason).

Thanks a lot for your feedback.

**Comment by AlbanShahajEFSA** [comment]
Yes it is possible to launch the tool in the Linux system but this will not be automatically updated since we are currently not supporting other operating systems except for Windows OS.

For launching the tool in Linux please download from the release page the "only app" package for your architecture. Once the donwload is completed extract the package and launch the ".jar" file (Java must be installed for this reason).

Thanks a lot for your feedback.

**Comment by AlbanShahajEFSA** [comment]
Yes it is possible to launch the tool in the Linux system but this will not be automatically updated since we are currently not supporting other operating systems except for Windows OS.

For launching the tool in Linux please download from the release page the "only app" package for your architecture. Once the donwload is completed extract the package and launch the ".jar" file (Java must be installed for this reason).

Thanks a lot for your feedback.
